- db/migrate/20220118053555_add_column_to_member.rb
- db/migrate/20220118053852_add_is_deleted_to_members.rb
- db/schema.rb
> add column-members

- Gemfile
- Gemfile.lock
- app/models/order.rb
- db/migrate/20220118060828_create_orders.rb
- test/fixtures/orders.yml
- test/models/order_test.rb
> modify bootsnap version

- app/models/jenre.rb
- db/migrate/20220118071058_create_jenres.rb
- db/migrate/20220118071248_add_column_to_jenre.rb
- db/schema.rb
- test/fixtures/jenres.yml
- test/models/jenre_test.rb
> create-jenre-model to column

- app/models/item.rb
- db/migrate/20220118071621_create_items.rb
- db/migrate/20220118071847_add_is_deleted_to_item.rb
- db/schema.rb
- test/fixtures/items.yml
- test/models/item_test.rb
> add items-model

- app/models/order.rb
- app/models/order_detail.rb
- config/application.rb
- config/locales/ja.yml
- db/schema.rb
> enum_order-order_details_japanese

- db/migrate/20220118090807_add_column_to_order_details.rb
- db/schema.rb
> order-detail-add-column

- app/models/address.rb
- app/models/cart.rb
- app/models/item.rb
- app/models/jenre.rb
- app/models/member.rb
- app/models/order.rb
- app/models/order_detail.rb
> relationship

- app/assets/javascripts/public/members.coffee
- app/assets/stylesheets/public/members.scss
- app/controllers/public/members_controller.rb
- app/helpers/public/members_helper.rb
- app/views/publics/sessions/new.html.erb
- db/schema.rb
- test/controllers/public/members_controller_test.rb
Reverts fried-chicken-lovers/nagano-cake#20
schemaのマージを取り消します。
> Revert "m-login/out"

- app/assets/javascripts/admin/items.coffee
- app/assets/stylesheets/admin/items.scss
- app/controllers/admin/items_controller.rb
- app/controllers/admins/sessions_controller.rb
- app/helpers/admin/items_helper.rb
- app/models/item.rb
- app/views/admin/items/index.html.erb
- db/schema.rb
- db/seeds.rb
- test/controllers/admin/items_controller_test.rb
管理者サイドの商品一覧画面作成、ログイン、ログアウト機能実装
> admin-items-index-login-logout

- app/controllers/admin/genres_controller.rb
- app/views/admin/genres/edit.html.erb
> 管理者ジャンルの編集機能

- app/models/member.rb
- app/views/admin/members/index.html.erb
> [Done]admin-members-index

- app/views/admin/members/show.html.erb
- config/routes.rb
> [Done]admin-members-show

- app/controllers/admin/items_controller.rb
- app/controllers/admin/members_controller.rb
- app/views/admin/items/index.html.erb
- app/views/admin/members/edit.html.erb
- app/views/admin/members/show.html.erb
> Admin members edit

- app/controllers/admin/items_controller.rb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/index.html.erb
> 管理者商品編集画面と編集

- app/controllers/public/delivery_addresses_controller.rb
- app/views/public/delivery_addresses/edit.html.erb
- app/views/public/delivery_addresses/index.html.erb
- app/views/public/members/show.html.erb
- config/routes.rb
- db/migrate/20220120092407_add_member_id_to_addresses.rb
- db/schema.rb
配送先登録、削除、編集機能を実装しました。
schemaにmember_idカラムを追加したため、rails db:migrate を行ってから作業をお願いします。
> 配送先の登録機能実装

- app/assets/javascripts/public/items.coffee
- app/assets/stylesheets/public/items.scss
- app/controllers/public/items_controller.rb
- app/helpers/public/items_helper.rb
- app/views/admin/items/index.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
- db/migrate/20220122043646_add_amount_to_items.rb
- db/schema.rb
- test/controllers/public/items_controller_test.rb
> [Done]public-items-index-show

- app/controllers/public/members_controller.rb
- app/controllers/publics/sessions_controller.rb
- app/models/member.rb
- app/views/public/members/edit.html.erb
- app/views/public/members/quit.html.erb
- app/views/public/members/unsubscribe.html.erb
- db/schema.rb
> members#action

- app/controllers/admin/genres_controller.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/index.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/members/show.html.erb
- app/views/public/delivery_addresses/edit.html.erb
- app/views/public/delivery_addresses/index.html.erb
- db/schema.rb
> ここにあるビューファイルのボタンにBootstrapを効かせました

- app/controllers/public/cart_items_controller.rb
- app/controllers/public/items_controller.rb
- app/models/cart.rb
- app/views/public/cart_items/index.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
- db/schema.rb
> カート一覧画面に削除機能を追加

- app/controllers/public/orders_controller.rb
- app/views/public/orders/thanx.html.erb
- config/routes.rb
> ご注文ありがとう画面[2回目]

- app/controllers/public/orders_controller.rb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
- db/schema.rb
> order#comfirm

- app/controllers/public/members_controller.rb
- app/controllers/public/orders_controller.rb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
> Order-function

- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
- app/views/public/orders/thanx.html.erb
> orders#design

- app/views/public/cart_items/index.html.erb
> カート画面にbootstrap

- app/controllers/public/members_controller.rb
- app/controllers/publics/registrations_controller.rb
- app/views/publics/registrations/new.html.erb
- app/views/publics/sessions/new.html.erb
> ログイン画面整えました

- app/controllers/admin/order_details_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/public/orders_controller.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/admin/orders/show.html.erb
- app/views/public/orders/new.html.erb
- config/locales/ja.yml
> 管理者側のユーザーの注文履歴詳細完成

- app/controllers/admin/orders_controller.rb
- app/controllers/public/orders_controller.rb
- app/views/admin/orders/index.html.erb
- app/views/admin/orders/show.html.erb
- app/views/public/orders/index.html.erb
- db/schema.rb
> Admin orders history index

- app/views/public/members/show.html.erb
- app/views/publics/sessions/new.html.erb
> member#show design

- app/controllers/admin/items_controller.rb
- app/controllers/public/members_controller.rb
- app/controllers/public/orders_controller.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/admin/orders/index.html.erb
- config/locales/ja.yml
- db/migrate/20220118060828_create_orders.rb
- db/migrate/20220119115659_bbb.rb
- db/migrate/20220125065017_aaa.rb
- db/schema.rb
> Admin-order-index-status

- app/controllers/admin/orders_controller.rb
- app/controllers/public/orders_controller.rb
- app/views/public/orders/show.html.erb
- config/application.rb
- config/locales/ja.yml
> public 注文詳細　　

- app/views/public/items/index.html.erb
> 会員の商品一覧で画像をクリックした後の遷移先を修正

- app/views/public/orders/show.html.erb
注文履歴のviewファイルに　_i18n　だけ追加しました。
> 注文履歴のviewを訂正

- app/controllers/public/orders_controller.rb
- app/views/public/orders/confirm.html.erb
- config/locales/ja.yml
> 会員の注文情報の修正

- app/views/admin/orders/index.html.erb
> 注文履歴一覧画面修正

- app/controllers/application_controller.rb
- app/controllers/publics/sessions_controller.rb
- app/models/member.rb
- app/views/admin/members/index.html.erb
- app/views/admins/sessions/new.html.erb
> [Done]Last
